[WIP] Filings/Reports panel amendment information
18F/openFEC-web-app pull request #1796
Opened 2017-01-17 10:15 UTC by xtine

This adds amendment information to the modal panel on filings and reports pages.
<img width="490" alt="screen shot 2017-01-17 at 3 09 32 am" src="https://cloud.githubusercontent.com/assets/24054/22016334/27716782-dc63-11e6-8f9f-751188f7122e.png">

https://github.com/18F/openFEC-web-app/issues/1738

2017-01-27 20:43 UTC, noahmanger commented
@xtine is this still in progress or should I review and merge?

2017-01-27 20:57 UTC, xtine commented
It's still in progress. There's still some minor things to be added, but also waiting for OK that there's cleaner amendment status data.

2017-01-31 02:40 UTC, dogweather requested changes

2017-01-31 02:40 UTC, dogweather commented on static/js/modules/helpers.js
> +function amendmentVersion(data) {
Could there be some variable name that'd be more expressive than `data`? It seems like a flag for whether the version is the current one. So maybe, `isCurrent`?

2017-01-31 02:40 UTC, dogweather commented on static/js/modules/helpers.js
> +    if (row.amendment_indicator === 'N') {
It'd be great to see the magic value `'N'` refactored from here.

2017-01-31 02:40 UTC, dogweather commented on static/js/modules/helpers.js
> +  // because of messy data, do not show if not e-filing or null amendment indicator
IMO an expressive guard clause would obviate the redundant comment, capture the described logic more clearly, and result in less nesting. E.g.,

```javascript
// Don't show if we don't have the appropriate data
if (row.means_filed !== 'e-file' || row.amendment_indicator === null {
  return '',
}
```

2017-01-31 02:40 UTC, dogweather commented on static/js/modules/helpers.js
> +    if (row.amendment_indicator === 'N') {
Also, the magic string `'e-file'`.

2017-01-31 03:15 UTC, xtine commented on static/js/modules/helpers.js
> +    if (row.amendment_indicator === 'N') {
`N` and `e-file` are variables returned from the API. How would I refactor that?

2017-01-31 03:17 UTC, xtine commented on static/js/modules/helpers.js
> +function amendmentVersion(data) {
I changed the variable to the more descriptive (and what the parameter is actually returned from API) `most_recent`.

2017-01-31 03:21 UTC, xtine commented on static/js/modules/helpers.js
> +  // because of messy data, do not show if not e-filing or null amendment indicator
Thanks for the suggestion! I didn't want to nest much but didn't think of a cleaner way at the moment.

2017-01-31 06:54 UTC, noahmanger requested changes
Looking mostly good, functionality wise. Had a few questions and made a small commit fixing a bug on committee page filings tables.

2017-01-31 06:54 UTC, noahmanger commented on openfecwebapp/templates/partials/filings-filter.html
> +      <fieldset class="js-filter js-filter-control" data-filter="checkbox" data-modifies-filter="most_recent" data-modifies-property="dataset">
Do you need the `js-filter-control` class and `data-modifies-*` attributes? Those are used when a filter needs to prompt a change in another one, iirc.

2017-01-31 06:54 UTC, noahmanger commented on openfecwebapp/templates/partials/reports-filter.html
> +            <input id="amendment_indicator_original" name="amendment_indicator" type="checkbox" value="N">
I noticed that this filter doesn't seem to be supported by the API. Should check with @jontours .

2017-01-31 06:54 UTC, noahmanger commented on static/js/modules/filings.js
> +      result.amendment_version = helpers.amendmentVersion(result.most_recent);
I think you need this same thing on the reports pages. It's missing from the panels.

2017-01-31 06:54 UTC, noahmanger commented on static/js/pages/filings.js
> +  $('.panel__navigation').hide();
Why hide instead of just removing from the templates?

2017-01-31 07:02 UTC, xtine commented on static/js/pages/filings.js
> +  $('.panel__navigation').hide();
Because the template is generic and then will remove it from other pages.

2017-01-31 19:15 UTC, xtine commented on openfecwebapp/templates/partials/filings-filter.html
> +      <fieldset class="js-filter js-filter-control" data-filter="checkbox" data-modifies-filter="most_recent" data-modifies-property="dataset">
You're correct, I forgot to remove them.

2017-01-31 21:54 UTC, dogweather commented on static/js/modules/helpers.js
> +    if (row.amendment_indicator === 'N') {
I think probably with constants. Roughly like,

```javascript
Api = {}
Api.MEANS_E_FILED = 'e-file'
Api.AMENDMENT_INDICATOR_NEW = 'N'
```

This way, the API is defined in just one place and misspellings are more likely to get caught:

```javascript
if (row.means_filed === Api.MEANS_E_FILED)
```

2017-02-01 03:40 UTC, xtine commented on static/js/modules/filings.js
> +      result.amendment_version = helpers.amendmentVersion(result.most_recent);
Just added to panels on reports.

2017-02-01 03:41 UTC, xtine commented
This is ready for another review to get into release. @noahmanger

2017-02-01 18:34 UTC, noahmanger reviewed
Looks good to me. Caught one small thing.

2017-02-01 18:34 UTC, noahmanger commented on static/templates/reports/pac.hbs
>        (This report has been amended)
Let's remove this part from all these templates. Redundant with the other new info.

2017-02-01 18:34 UTC, noahmanger commented on static/templates/reports/pac.hbs
>        (This report has been amended)
(Note, these are in the other panel templates as well).

2017-02-01 18:34 UTC, noahmanger commented on static/js/pages/filings.js
> +  $('.panel__navigation').hide();
👍

2017-02-01 18:59 UTC, xtine commented on static/templates/reports/pac.hbs
>        (This report has been amended)
With the rollback on amendment info on reports, we'll have to keep this in for reports panels.

2017-02-01 19:06 UTC, noahmanger approved these changes

2017-02-01 19:12 UTC, noahmanger commented
Looks like @dogweather 's comments have been addressed but just want to give him a ping to approve if everything looks good.

2017-02-01 19:37 UTC, dogweather approved these changes

2017-02-01 19:37 UTC, dogweather commented
Excellent! Yep, looks great.

2017-02-01 19:38 UTC, noahmanger commented
Bingo. Thanks!

2017-02-01 19:38 UTC, merged