[WIP] Feature/itemized loans
18F/openFEC-web-app pull request #1828
Opened 2017-02-08 17:40 UTC by johnnyporkchops

Itemized loans datatable 
Issue: https://github.com/18F/openFEC-web-app/issues/1613

2017-02-08 21:09 UTC, xtine commented on openfecwebapp/templates/partials/itemized-loans-filter.html
> +  {{ text.field('loan_source_name', 'Loaner name') }}
Include the filters within the `js-accordion` block to give them the filter padding.

2017-02-08 21:09 UTC, xtine commented on static/js/pages/itemized-loans.js
> +var helpers = require('../modules/helpers');
You can remove the line since there aren't any helper functions being called.

2017-02-08 21:09 UTC, xtine commented on static/js/pages/itemized-loans.js
> +    //path: ['loans', 'get_schedules_schedule_c'],
Make sure to remove these comments.

2017-02-11 01:02 UTC, noahmanger requested changes
Looking good. Just had a few notes and questions.

2017-02-11 01:02 UTC, noahmanger commented on openfecwebapp/templates/partials/loans-filter.html
> +{% import 'macros/filters/years.html' as years %}
Don't need the years macro.

2017-02-11 01:02 UTC, noahmanger commented on openfecwebapp/templates/partials/loans-filter.html
> +{% import 'macros/filters/ie-reports.html' as reports %}
Don't need ie-reports macro

2017-02-11 01:02 UTC, noahmanger commented on openfecwebapp/templates/partials/loans-filter.html
> +{% import 'macros/filters/states.html' as states %}
Don't need states macro.

2017-02-11 01:02 UTC, noahmanger commented on static/js/modules/columns.js
> +    render: function (data, type, row) {
This `render` function should also build a link to the page, like the other tables do:
```js
      if (data) {
        return columnHelpers.buildEntityLink(
          data.name,
          helpers.buildAppUrl(['committee', data.committee_id]),
          'committee'
        );
      } else {
        return '';
      }
```

2017-02-11 01:02 UTC, noahmanger commented on static/js/modules/columns.js
> +  dateColumn({data: 'load_date', orderable: true, className: 'min-tablet hide-panel column--med'}),
I'm not sure what the value for the `date` column should be, but I don't think `load_date` is right, as that's just about when it was loaded into the system. @PaulClark2, when displaying a table of itemized schedule Cs, should we show a date? And if so, the date of what?

2017-02-11 01:18 UTC, noahmanger commented
Also, I added docs here to explain how to get the details panel working. https://github.com/18F/openFEC-web-app/wiki/Datatable-Page-Setup#create-a-details-panel-template

2017-02-11 02:37 UTC, xtine commented
I got the details panel working on my Debts PR (https://github.com/18F/openFEC-web-app/pull/1824) for reference. /cc @patphongs

2017-02-13 12:22 UTC, PaulClark2 commented on static/js/modules/columns.js
> +  dateColumn({data: 'load_date', orderable: true, className: 'min-tablet hide-panel column--med'}),
This is for the details panel, right? There are two dates we should probably show if there is room, `Date Incurred` and 'Date Due`.

2017-02-13 17:06 UTC, noahmanger commented on static/js/modules/columns.js
> +  dateColumn({data: 'load_date', orderable: true, className: 'min-tablet hide-panel column--med'}),
What about in the table? Is there one that makes more sense to use for sorting?

2017-02-15 17:05 UTC, PaulClark2 commented on static/js/modules/columns.js
> +  dateColumn({data: 'load_date', orderable: true, className: 'min-tablet hide-panel column--med'}),
`Date Incurred`

2017-02-15 19:59 UTC, johnnyporkchops commented on static/js/modules/columns.js
> +  dateColumn({data: 'load_date', orderable: true, className: 'min-tablet hide-panel column--med'}),
There does not seem to be a Date Due field in the data for itemized-loans

2017-02-16 18:17 UTC, noahmanger approved these changes

2017-02-16 18:22 UTC, merged